### ISSUE TITLE
Docker compose (no domain, just IP address) - application runs, but none of the endpoints work

### ISSUE THREAD

**Issue by bro1** [bohwaz/micro-gpodder-server#18]
Hi,

I am trying to run the latest head version (commit fa5607bf4de491ff8cf0fdb3881a1126e009a296) in a docker.

Application is starting and displaying home page, but none of the links do anything:

![Screenshot from 2024-01-28 16-16-10](https://github.com/bohwaz/micro-gpodder-server/assets/397284/ed8dd255-76be-4bdd-976d-ab6fe629e4c7)

Here is my docker compose:
```
services:
  gpodder:
    container_name: gPodder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /home/bro1/docker_files/gpodder/data
        target: /var/www/server/data
    hostname: 192.168.68.62
    ports:
      - 8099:80
```

Here is the log from console:

```
x@linaslaptop:~/opt/micro-gpodder-server$ sudo docker-compose up 
Starting gPodder ... done
Attaching to gPodder
gPodder    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.68.62. Set the 'ServerName' directive globally to suppress this message
gPodder    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.68.62. Set the 'ServerName' directive globally to suppress this message
gPodder    | [Sun Jan 28 03:19:11.958740 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) PHP/8.2.15 configured -- resuming normal operations
gPodder    | [Sun Jan 28 03:19:11.958788 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
gPodder    | 172.19.0.1 - - [28/Jan/2024:03:19:16 +0000] "GET /register HTTP/1.1" 200 614 "http://localhost:8099/register" "Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"
gPodder    | 172.19.0.1 - - [28/Jan/2024:03:19:16 +0000] "GET /style.css HTTP/1.1" 200 1432 "http://localhost:8099/register" "Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"
gPodder    | 172.19.0.1 - - [28/Jan/2024:03:19:17 +0000] "GET /icon.svg HTTP/1.1" 304 248 "http://localhost:8099/register" "Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"
gPodder    | 172.19.0.1 - - [28/Jan/2024:03:19:18 +0000] "GET /login HTTP/1.1" 200 613 "http://localhost:8099/register" "Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"
```

Do you have any advice?

**Comment by iampegram** [comment]
It appears as though the sample docker-compose wasn't updated when the Dockerfile changed where the server files were copied. the `volumes` section should read:
```
volumes:
- type: bind
  source: /path/to/data
  target: /var/www/html/data
```
Of course, that throws a new error (for me, at least). I'm guessing I don't have the right permissions set on the folder, because the database file can't be created.
